CREATE TABLE tb_roles(
    role_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(50) NOT NULL,
    PRIMARY KEY(role_id)
);

CREATE TABLE tb_categories(
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(50) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE tb_users(
    enabled boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id uuid NOT NULL,
    password varchar(72) NOT NULL,
    email varchar(100) NOT NULL,
    name varchar(150),
    PRIMARY KEY(user_id)
);

CREATE TABLE tb_sales(
    total_value numeric(10,2) NOT NULL,
    sale_date timestamp with time zone NOT NULL,
    sale_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sale_channel varchar(30) NOT NULL,
    client varchar(150),
    PRIMARY KEY(sale_id),
    CONSTRAINT tb_sales_sale_channel_check CHECK (((sale_channel)::text = ANY ((ARRAY['SHOPEE'::character varying, 'LOCAL'::character varying, 'INSTAGRAM'::character varying, 'WHATSAPP'::character varying])::text[])))
);

CREATE TABLE tb_users_roles(
    role_id bigint NOT NULL,
    user_id uuid NOT NULL,
    PRIMARY KEY(role_id,user_id),
    CONSTRAINT fkj5qged12p22eloqw5g4f9hm2e FOREIGN key(role_id) REFERENCES tb_roles(role_id),
    CONSTRAINT fk5xc4yvfrjcy8bl01kq3crp8pg FOREIGN key(user_id) REFERENCES tb_users(user_id)
);

CREATE TABLE tb_tokens(
    expiry_date timestamp with time zone NOT NULL,
    id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
    user_id uuid NOT NULL,
    ip varchar(50),
    token varchar(255) NOT NULL,
    token_hash varchar(255),
    user_agent varchar(255),
    PRIMARY KEY(id),
    CONSTRAINT fk3fcij8v8087hgliwvxdh5w9o1 FOREIGN key(user_id) REFERENCES tb_users(user_id)
);

CREATE TABLE tb_products(
    price numeric(10,2),
    quantity_stock integer,
    category_id bigint NOT NULL,
    created_at timestamp with time zone,
    product_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    color varchar(50),
    name varchar(100),
    description varchar(500),
    PRIMARY KEY(product_id),
    CONSTRAINT fkcthu194f0icof6cxprcukmotk FOREIGN key(category_id) REFERENCES tb_categories(id)
);

CREATE TABLE tb_sale_items(
    quantity integer NOT NULL,
    sub_total numeric(10,2) NOT NULL,
    unit_at_price numeric(10,2) NOT NULL,
    product_id bigint NOT NULL,
    sale_id bigint NOT NULL,
    sale_item_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    PRIMARY KEY(sale_item_id),
    CONSTRAINT fkpi5gu1athqg5kh6eolvbt6fka FOREIGN key(product_id) REFERENCES tb_products(product_id),
    CONSTRAINT fkqog2klb305rck1prcq1qksugt FOREIGN key(sale_id) REFERENCES tb_sales(sale_id)
);

-- INSERÇÃO DE DADOS ESTÁTICOS (ROLES)
-- O comando agora funciona sem OVERRIDING SYSTEM VALUE
INSERT INTO tb_roles (role_id, name) VALUES (1, 'ADMIN')
ON CONFLICT (role_id) DO NOTHING;

INSERT INTO tb_roles (role_id, name) VALUES (2, 'BASIC')
ON CONFLICT (role_id) DO NOTHING;